[package]
name = "lanpatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.9"
tracing = "0.1.41"
rhai = { version = "1.20.1", features = ["sync"] }
serde = { version = "1.0.216", features = ["derive"] }
walkdir = "2.5.0"
