[package]
name = "lanpatch"
version = "0.1.0"
edition = "2021"

[dependencies]
rhai = "1.20.1"
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["rt", "fs", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
